// USER REDUCER TYPES
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';

// UI REDUCER TYPES
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';

// DATA REDUCER TYPES
export const SET_KHABARS = 'SET_KHABARS';
export const SET_KHABAR = 'SEt_KHABAR';
export const LIKE_KHABAR = 'LIKE_KHABAR';
export const UNLIKE_KHABAR = 'UNLIKE_KHABAR';
export const DELETE_KHABAR = 'DELETE_KHABAR';
export const POST_KHABAR = 'POST_KHABAR';
export const SUBMIT_COMMENT = 'SUBMIT_COMMENT';